
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfGenerator {
  /// Helper to load a Unicode-compatible font (Roboto)
  static Future<pw.ThemeData> _buildTheme() async {
    final font = await PdfGoogleFonts.robotoRegular();
    final boldFont = await PdfGoogleFonts.robotoBold();
    return pw.ThemeData.withFont(
      base: font,
      bold: boldFont,
    );
  }

  static Future<void> generateInstitutionalReport({
    required Map<String, int> stats,
    required Map<String, int> deptCounts,
    required String title,
  }) async {
    final theme = await _buildTheme();
    final pdf = pw.Document(theme: theme);

    // Load logo if available (optional)
    pw.MemoryImage? logo;
    try {
      final logoBytes = await rootBundle.load('assets/app_logo3.png');
      logo = pw.MemoryImage(logoBytes.buffer.asUint8List());
    } catch (e) {
      // Fallback: no logo if image doesn't exist
    }

    final date = DateFormat('MMMM dd, yyyy').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('ScholarDoc Institution Analytics', 
                      style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                    pw.SizedBox(height: 4),
                    pw.Text('Official Institutional Document', 
                      style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                  ],
                ),
                if (logo != null) pw.Image(logo, width: 60),
              ],
            ),
            pw.Divider(thickness: 1.5, color: PdfColors.blueGrey100),
            pw.SizedBox(height: 24),

            // Report Meta
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Report Title: $title', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text('Date: $date', style: pw.TextStyle(color: PdfColors.grey700)),
              ],
            ),
            pw.SizedBox(height: 32),

            // Summary Stats
            pw.Text('Institutional Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 16),
            pw.Row(
              children: [
                _buildStatBox('Total Registered', stats['total']?.toString() ?? '0', PdfColors.blue50),
                pw.SizedBox(width: 12),
                _buildStatBox('Approved', stats['approved']?.toString() ?? '0', PdfColors.green50),
                pw.SizedBox(width: 12),
                _buildStatBox('Rejected', stats['rejected']?.toString() ?? '0', PdfColors.red50),
              ],
            ),
            pw.SizedBox(height: 32),

            // Department Breakdown Table
            pw.Text('Department Breakdown', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 16),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                  children: [
                    _tableHeader('Department / Course'),
                    _tableHeader('Active Students'),
                    _tableHeader('Percentage (%)'),
                  ],
                ),
                ...deptCounts.entries.map((e) {
                  final total = stats['total'] ?? 1;
                  final percentage = ((e.value / total) * 100).toStringAsFixed(1);
                  return pw.TableRow(
                    children: [
                      _tableCell(e.key),
                      _tableCell(e.value.toString()),
                      _tableCell('$percentage%'),
                    ],
                  );
                }),
              ],
            ),
            pw.SizedBox(height: 48),

            // Footer / Signature placeholders
            pw.Spacer(),
            pw.Divider(thickness: 1, color: PdfColors.grey300),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Generated by: ScholarDoc Admin System', style: const pw.TextStyle(fontSize: 10)),
                    pw.Text('Authentication Hash: ${DateTime.now().millisecondsSinceEpoch.toRadixString(16).toUpperCase()}', 
                      style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                  ],
                ),
                pw.Column(
                  children: [
                    pw.Container(width: 150, height: 1, color: PdfColors.black),
                    pw.SizedBox(height: 4),
                    pw.Text('Registrar Signature', style: const pw.TextStyle(fontSize: 10)),
                  ],
                ),
              ],
            ),
          ];
        },
      ),
    );

    // Share or Save the PDF
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: '${title.replaceAll(' ', '_')}_$date.pdf',
    );
  }

  /// Generates a professional Audit Log report
  static Future<void> generateAuditReport({
    required List<Map<String, dynamic>> logs,
    required String filterSummary,
  }) async {
    final theme = await _buildTheme();
    final pdf = pw.Document(theme: theme);
    final date = DateFormat('MMMM dd, yyyy').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape, // Landscape for better table fit
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('System Audit Trail', 
                      style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                    pw.SizedBox(height: 4),
                    pw.Text('Security Compliance Document - Generated on $date', 
                      style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                  ],
                ),
              ],
            ),
            pw.SizedBox(height: 8),
            pw.Text('Filter Applied: $filterSummary', style: pw.TextStyle(fontSize: 9, fontStyle: pw.FontStyle.italic, color: PdfColors.grey600)),
            pw.Divider(thickness: 1.5, color: PdfColors.blueGrey100),
            pw.SizedBox(height: 20),

            // Logs Table
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey200, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(2.5), // Timestamp
                1: const pw.FlexColumnWidth(3),   // User
                2: const pw.FlexColumnWidth(2),   // Role
                3: const pw.FlexColumnWidth(6),   // Action
                4: const pw.FlexColumnWidth(2.5), // Target (Student ID)
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.blueGrey50),
                  children: [
                    _tableHeader('Timestamp'),
                    _tableHeader('User Name'),
                    _tableHeader('Role'),
                    _tableHeader('Action Taken'),
                    _tableHeader('Target ID'),
                  ],
                ),
                ...logs.map((log) {
                  final ts = log['timestamp'];
                  String dateStr = 'N/A';
                  if (ts != null) {
                    try {
                      final parsed = DateTime.parse(ts.toString());
                      dateStr = DateFormat('MM/dd HH:mm').format(parsed);
                    } catch (_) {}
                  }
                  
                  return pw.TableRow(
                    children: [
                      _tableCell(dateStr),
                      _tableCell(log['adminName'] ?? 'Unknown'),
                      _tableCell(log['role'] ?? 'Admin'),
                      _tableCell(log['action'] ?? '-'),
                      _tableCell(log['studentId'] ?? 'N/A'),
                    ],
                  );
                }),
              ],
            ),
            
            pw.SizedBox(height: 24),
            pw.Text('End of Audit Report', textAlign: pw.TextAlign.center, 
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Audit_Report_$date.pdf',
    );
  }

  static pw.Widget _buildStatBox(String label, String value, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: color,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
          border: pw.Border.all(color: PdfColors.grey200),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.black)),
            pw.SizedBox(height: 8),
            pw.Text(value, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey900)),
          ],
        ),
      ),
    );
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
    );
  }

  static pw.Widget _tableCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: const pw.TextStyle(fontSize: 9)),
    );
  }
}
